version: 2
jobs:
  build:
    docker:
    - image: lexifdev/circleci-python3-node-gcloud
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: deploy backend
          command: |
            cd backend
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            echo $GCLOUD_KEY_JSON > /home/circleci/.gcloud-key
            gcloud auth activate-service-account --key-file=/home/circleci/.gcloud-key
            gcloud config set project isnamyang
            gcloud -q app deploy app.yaml 
      - run:
          name: deploy frontend
          command: |
            cd frontend
            yarn install
            yarn run build
            yarn run deploy
